name: Deploy Live Channel on Firebase Hosting
run-name: ${{ github.actor }} merge/${{ github.event_name }} is deploying to production
on:
  push:
    branches:
      - main
jobs:

  build:
    name: Build for Production environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build-prod
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy to Production environment
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Production Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        id: hosting
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANGULAR_TESTS_37360 }}'
          channelId: live
          target: prod
          projectId: angular-tests-37360

  announce: 
    if: ${{ always() }}
    needs: [build, deploy]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: reediculous456/ms-teams-deploy-card@v1.1.0
        if: always()  
        with:
          github-token: ${{ github.token }}
          webhook-uri: ${{ secrets.MS_TEAMS_WEBHOOK_URI }}
          show-on-start: false
          card-layout-exit: "complete"
          timezone: "America/Mexico_City"
          view-status-action-text: "See action on GH"
          allowed-file-len: 10
          custom-actions: |
            - text: See deployment
              url: "https://bego.ai"
          custom-facts: |
            - name: Message
              value: "Pull recent changes to avoid conflicts"
            - name: Author
              value: ${{ github.actor }}
        env: 
          REVIEWERS: ${{ env.reviewers }}
          ASSIGNEES: ${{ env.assignees }}
      - name: Jobs failed
        if: ${{ needs.build.result != 'success' || needs.deploy.result != 'success' }}
        run: exit 1
      - name: Jobs succeeded
        if: ${{ needs.build.result == 'success' && needs.deploy.result == 'success' }}
        run: exit 0
