name: Deploy Preview Channel on Firebase Hosting
run-name: ${{ github.actor }} ${{ github.event_name }}/${{ github.event.action }} '#${{ github.event.pull_request.number }}' is deploying a preview channel
on: 
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - development
jobs:

  build:
    name: Build for QA environment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm ci
      - name: Build Script
        run: npm run build
      - name: Archive Build Artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist

  deploy:
    name: Deploy to QA environment
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download Build Artifact
        uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ANGULAR_TESTS_37360 }}'
          projectId: angular-tests-37360
          target: prev
          channelId: prev-pr${{ github.event.pull_request.number }}
          expires: 3d
